spring.application.name=blackjack
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
